name: Build Spring Boot with Gradle

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Permissão Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Construir Projeto
        run: ./gradlew build --no-daemon

      - name: Executar Testes
        run: ./gradlew test --no-daemon

      - name: Mostrar Usuário
        run: echo "BUILD EXECUTADO POR:" ${{ github.actor }}