name: Build Spring Boot with Gradle

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB:  ${{ secrets.POSTGRES_DATABASE }}
        ports:
          - 5432:5432

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Permissão Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Criar pasta para o arquivo de configuração
        run: mkdir -p  ${{ secrets.FOLDER_PATH }}

      - name: Copiar arquivo smartbrains.properties
        run: |
          cp  ${{ secrets.FILE_PATH }}

      - name: Construir Projeto
        run: ./gradlew build --no-daemon --info

      - name: Executar Testes e Gerar Relatório JaCoCo
        run: ./gradlew clean test jacocoTestReport --no-daemon --info

      - name: Usuário
        run: echo "BUILD EXECUTADO POR:" ${{ github.actor }}