name: Java with Gradle

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: SET UP JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Permission for Gradlew
        run: chmod +x gradlew

      - name: Clean with Gradle Wrapper
        run: ./gradlew clean

      - name: Build with Gradle Wrapper
        run: ./gradlew build
