jobs:
  build:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: smartbrains_test
        ports:
          - 5432:5432

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Permissão Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Criar pasta para o arquivo de configuração
        run: mkdir -p /home/runner/smartbrains

      - name: Copiar arquivo smartbrains.properties
        run: |
          cp ./dist/smartbrains.properties /home/runner/smartbrains/smartbrains.properties

      - name: Construir Projeto
        run: ./gradlew build --no-daemon

      - name: Executar Testes
        run: ./gradlew test --no-daemon

      - name: Usuário
        run: echo "BUILD EXECUTADO POR:" ${{ github.actor }}
